---
defaultBaseImageVersion: latest
private_worker:
  workerType: public
  workerId: public
  workerName: ''

properties:
- name: AATOOLCHAINNAME
  value: "{{toolchain.name}}"
  type: text
- name: PREFIX
  value: a100
  type: text
  
stages:
- name: MyStage
  worker: Worker[name=null,type=null,id=null]
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: Build
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
hooks:
- enabled: true
  label: null
  ssl_enabled: true
  url: https://devops-api.us-south.devops.cloud.ibm.com/v1/messaging/webhook/publish

