version: '2'
template:
  name: Continuous Delivery Toolchain for VPC Image Creation from Classic
  description: "This toolchain includes tools to develop and deploy your app. Depending on your app, when you create the toolchain, the GitHub repository will either be empty or will contain source code from your app.\n\nThis toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in your organization, when you click **Create**, it is automatically added at no cost to you. For more information and terms, see the [IBM Cloud catalog](/catalog/services/continuous-delivery/).\n\nTo get started, click **Create**."
  required:
    - repo
    - build

toolchain:
  name: 'vpc-toolchain-{{timestamp}}'

services:
  # Github repos
  repo:
    service_id: githubpublic
    parameters:
      source_repo_url: "https://github.com/powellquiring/vpc-tutorials"
      repo_name: "{{toolchain.name}}"
      type: link
      has_issues: false
      enable_traceability: false

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "FUN Name"
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          API_KEY: "{{form.pipeline.parameters.api-key}}"
        execute: false

#          PREFIX: "{{toolchain.name}}"

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
#      app-name: "{{app-name}}"
#      toolchain-name: "{{toolchain-name}}"
      vpc-region: "{{vpc-region}}"
#      vpc-ssh-key: "{{vpc-ssh-key}}"
#      target-resource-group: 'default'
      ssh-private-key: "{{ssh-private-key}}"
#      vpc-resources-prefix: "{{vpc-resources-prefix}}"
